name: "Change Impact Radar"
description: "Comments on PRs with an Impact Score (0–100) and 🟢/🟡/🔴 verdict based on structural amplification."

branding:
  icon: "activity"
  color: "purple"

inputs:
  github_token:
    description: "GitHub token with pull-requests:write (optional, defaults to GITHUB_TOKEN)."
    required: false
  max_depth:
    description: "Max dependency graph traversal depth."
    required: false
    default: "6"
  max_files:
    description: "Max number of repository files to scan for dependency graph."
    required: false
    default: "1200"
  include_globs:
    description: "Newline-separated glob patterns to include."
    required: false
    default: ""
  exclude_globs:
    description: "Newline-separated glob patterns to exclude."
    required: false
    default: |
      **/*.md
      **/*.txt
      **/*.png
      **/*.jpg
      **/*.jpeg
      **/*.gif
      **/*.svg
      **/*.pdf
      **/package-lock.json
      **/yarn.lock
      **/pnpm-lock.yaml
      **/dist/**
      **/node_modules/**
  hotspot_paths:
    description: "Newline-separated path prefixes treated as hotspots (e.g., src/, core/)."
    required: false
    default: |
      src/
      lib/
      core/
  comment_mode:
    description: "How to post PR comment: 'update' (default) or 'recreate'."
    required: false
    default: "update"
  fail_on_high:
    description: "If 'true', fails the job when verdict is 🔴."
    required: false
    default: "false"
  debug:
    description: "If 'true', prints debug logs."
    required: false
    default: "false"

outputs:
  impact_score:
    description: "Final impact score (0-100)."
  verdict:
    description: "Verdict label (e.g. '🟢 Low impact', '🟡 Medium impact', '🔴 High impact')."
  verdict_emoji:
    description: "Verdict emoji only (🟢/🟡/🔴)."
  css:
    description: "Change Size Score (0-100)."
  drs:
    description: "Dependency Reach Score (0-100)."
  hcs:
    description: "Hotspot & Coupling Score (0-100)."
  af:
    description: "Amplification Factor (can be negative; range approx -100..100)."
  comment_url:
    description: "URL of the created/updated PR comment (if available)."

runs:
  using: "node20"
  main: "dist/index.js"


